### ISSUE TITLE
Feature - Save the current state in browser

### ISSUE THREAD

**Issue by LucasVbr** [RemiSaurel/own-workspace#6]
Hi Remi, I really like your web app and I will surely use it during my study sessions.
That's why I suggest you a feature that could be really helpful as a user!

# Example
You start a session and you accidentally close the tab...
> Oh my god, I lost all my to-dos and working time! 😱

# Feature
The data that it could be handful to save on browser:
- To-do list items
- Remaining work time
- Stats of the session
- Current word definition
- Current video you watch

You can for example use the Javascript [localStorage](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage) or a database like [FireBase](https://firebase.google.com/).

**Comment by LucasVbr** [comment]
In my opinion, both options are valid, but I prefer the first.
It's maybe more code for not much.
So, it depends on the users and how they use your app.

**Comment by RemiSaurel** [comment]
The feature is working on dev branch. Going to merge it soon. 

## ✨ New saved elements
- Todos list with the order, and pinned elements
- Stats with last sessions number of todos closed + number of pomodoro sessions
- Current song playing
- Current colour selected

### Not saving current Pomodoro Timer, why ?
I didn't want the timer to be saved since the major cases of people closing the tab = finished their session. 
Why not the same for todo list? It will force you to either "finish" your task OR keep it in mind

### Evolutions possible
- Storage in databases for deeper analyses 
- Personal account customization
